### ISSUE TITLE
I'm looking for a front end dev

### ISSUE THREAD

**Issue by johndpope** [a1exalexander/exchanger#1]
Do you have a business (that you can invoice throught) ? 
What are your rates? availability / hours per week?

**Comment by a1exalexander** [comment]
Hi! 
I can give you my contacts
[Facebook](https://www.facebook.com/a1exalexander)
alexander.ratushnyi@gmail.com

and my team contacts
https://merge.rocks/
[Facebook](https://www.facebook.com/mergedevt/)
